Today is Day-97 of #100DaysOfCode

Displaying webcam feed using opencv and python .

In [ ]:
import cv2

cv2.namedWindow("preview")
vc = cv2.VideoCapture(0)  #cap.release() 

if vc.isOpened(): # try to get the first frame
    rval, frame = vc.read()
else:
    rval = False

while rval:
    cv2.imshow("preview", frame)
    rval, frame = vc.read()
    key = cv2.waitKey(20)
    if key == 27: # exit on ESC
        break
cv2.destroyWindow("preview")

To turn off the camera, restart the kernal.

Next using Numpy, Reshaping and flatten the data.

In [3]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)   #reshape the data

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
e.flatten()  #flatten data

array([1, 2, 3, 4, 5, 6])